apiVersion: apps/v1
kind: Deployment
metadata:
  name: seeds
spec:
  selector:
    matchLabels:
      app: seeds
  replicas: 3
  template:
    metadata:
      labels:
        app: seeds
    spec:
      containers:
      - name: seeds
        image: nats
        args: 
        - "--cluster"
        - "nats://0.0.0.0:6222"
        - "--cluster_name"
        - "default_cluster"
        - "-m"
        - "8222"
        ports:
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor  
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: monitor
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        startupProbe:
          failureThreshold: 90
          httpGet:
            path: /healthz
            port: monitor
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: seeds
spec:
  clusterIP: None
  ports:
  - port: 6222
    targetPort: 6222
    protocol: TCP
  selector:
    app: seeds